version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: productmanagement-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SqlPassword123
      - MSSQL_PID=Express
    ports:
      - "1435:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: